rethinkdb-dev:
  image: rethinkdb:2.3.4
  ports:
    - "8080:8080"
    - "28015:28015"
    - "29015:29015"
  volumes:
    - ./.volumes/data-dev:/data


rethinkdb-test:
  image: rethinkdb:2.3.4
  ports:
    - "38080:8080"
    - "38015:28015"
    - "39015:29015"
  volumes:
    - ./.volumes/data-test:/data
