app:
  build: .
  ports:
    - "3000:3000"
  environment:
    - RETHINK_HOST=rethinkdb
    - RETHINK_PORT=28015
    - RETHINK_DB="pico_chat"
  links:
    - rethinkdb

rethinkdb:
  image: rethinkdb:2.3.4
  volumes:
    - ./.volumes/data:/data
